language: python

sudo: required

services:
  - docker

python:
  - "3.5"
  - "3.6"
  - "nightly"

install:
  - pip install sphinx
  - python setup.py install

# TODO: replace this with a bonafide test suite
script:
  - bugzoo -h
  - bugzoo tool -h
  - bugzoo source -h
  - bugzoo bug -h
  - bugzoo container -h
  - bugzoo tool list
  - bugzoo source list
  - bugzoo bug list
  - bugzoo dataset list
  - python3 test/test_manybugs.py

before_deploy:
  - (cd docs && make html && cd _build/html && touch .nojekyll)

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/_build/html
  github_token: $GITHUB_TOKEN
  on:
    branch: docs
    python: 3.6
